/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminImagePicker: typeof import('./src/components/AdminImagePicker/index.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppLogos: typeof import('./src/components/AppLogos.vue')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    GoodsCard: typeof import('./src/components/GoodsCard.vue')['default']
    InputEntry: typeof import('./src/components/InputEntry.vue')['default']
    PageLoading: typeof import('./src/components/PageLoading/index.vue')['default']
    SubmitBar: typeof import('./src/components/SubmitBar.vue')['default']
  }
}
